apiVersion: apps/v1
kind: Deployment
metadata:
  name: tidb-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tidb
  template:
    metadata:
      labels:
        app: tidb
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: tidb
          image: pingcap/tidb:latest
          ports:
            - containerPort: 4000
            - containerPort: 10080
              name: metrics
          env:
            - name: TIDB_STORE
              value: "unistore"
            - name: TIDB_PATH
              value: "/tmp/tidb"
          command:
            - /tidb-server
          args:
            - --store=unistore
            - --path=/tmp/tidb
            - --log-slow-query=/tmp/tidb/tidb-slow.log
            - --status=10080
          volumeMounts:
            - name: tidb-data
              mountPath: /tmp/tidb
      volumes:
        - name: tidb-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tidb-service
  namespace: demo
spec:
  selector:
    app: tidb
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
      protocol: TCP
      name: tidb-port
    - port: 10080
      targetPort: 10080
      nodePort: 30500
      protocol: TCP
      name: metrics-port
  type: NodePort
