global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  # Spring Boot Application with Actuator
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8080"]

  - job_name: "tidb"
    static_configs:
      - targets: ["tidb:10080"]
